### ISSUE TITLE
Disconnect from MQTT Server when Ping Response is not received for considerable amount of time

### ISSUE THREAD

**Issue by mvkarthikeyan** [eclipse/paho.mqtt.embedded-c#152]
As per specification of MQTT 3.1.1 client was supposed to get disconnect from server when  ping response is not received .
" If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server." 
please check here  http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349238

**Comment by scaprile** [comment]
According to RFC-2119, which MQTT3.1.1 cites as the definitions for its terminology usage, the word SHOULD means:
"_SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course._"
So, it is not mandatory to do that, the application must understand what is going on and make a decision whether to close the connection or not. The current behaviour is not necessarily incorrect... though ignoring this fact is probably not good either.
There can be some transitory network conditions that are delaying communications and adding the connection setup burden can only make things worse, particularly on very slow networks. The client does not know anything about the type of network, the application should know better.
In such a case, it would preferable to make the client inform the application, so it may choose whether to close the connection or not.
I guess that is one reason for the usage of SHOULD instead of MUST.

**Comment by icraggs** [comment]
I think the two client libraries do implement this behaviour.  See the keepalive function in the C and C++ versions of MQTTClient.

It's not a disconnect from the server, by the way, but the client should close the TCP connection.

**Comment by icraggs** [comment]
I think this has been answered. Other issues cover some problems with the keepalive processing.
