### ISSUE TITLE
A networked error on .read() will not make the client disconnected.

### ISSUE THREAD

**Issue by 256dpi** [eclipse/paho.mqtt.embedded-c#36]
Hi again,

I found another issue while working on the arduino-mqtt library.

It looks like that errors from the `read()` method in the Network class do not traverse up in the client and set the internal flag to disconnected. This has the effect that clients, that never send any packets and only read from the connection, never change the internal "connected" flag if the underlying connection fails.

A fix would be to set the client to disconnected if any serious errors happen while reading from the underlying connection. That way, a future call to `isConnected()` would correctly return `false`.

**Comment by 256dpi** [comment]
Is somebody interested in looking at that?

**Comment by icraggs** [comment]
I've updated the code that uses read() so that it correctly uses these return values:
-1: connection error, isConnected should then return false
0: zero bytes received within the time available, no connection error
>0: the number of bytes received, no connection error

This works on Linux, I'm not sure about the Arduino read() implementation following these requirements properly.

**Comment by icraggs** [comment]
I've added a test for disconnection which works on Linux.   All that remains is to check it works on Arduino.

**Comment by ppescher** [comment]
@icraggs for Arduino see #205

**Comment by icraggs** [comment]
Superseded by #205
